### ISSUE TITLE
relationship to zanders3/glwt

### ISSUE THREAD

**Issue by benswift** [rikusalminen/glwt#9]
I'm just wondering what the relationship between this project and https://github.com/zanders3/glwt is?

Is it just that this one is C while the other one is C++?  Are they both still under active development?

**Comment by rikusalminen** [comment]
These projects have nothing in common except the name.

GLWT is still under development but very inactive due to time constraints and other projects we're working on. We would welcome contributors. In particular, Windows support needs more work.
